LEAGUE_TABLE_RENAME_COL_DICT = {
    "rk": "position",
    "squad": "team",
    "mp": "matches_played",
    "w": "wins",
    "d": "draws",
    "l": "losses",
    "gf": "goals_for",
    "ga": "goals_against",
    "gd": "goal_difference",
    "pts": "points",
    "pts_per_mp": "points_per_match",
    "xg": "xg",
    "xga": "xg_against",
    "xgd": "expected_goal_difference",
    "xgd_per_90": "expected_goal_difference_per_90",
    "gls_per_game": "goals_per_game",
    "gls_conceded_per_game": "gls_conceded_per_game",
    "xg_per_game": "xg_per_game",
    "xga_per_game": "xg_against_per_game",
}

PLAYER_STANDARD_RENAME_COL_DICT = {
    "rk": "rank",
    "player": "player_name",
    "nation": "country",
    "pos": "position",
    "squad": "team",
    "comp": "competition",
    "age": "age",
    "born": "born",
    "playing_time_mp": "matches_played",
    "playing_time_starts": "starts",
    "playing_time_min": "minutes",
    "playing_time_90s": "no_of_nineties",
    "performance_gls": "goals",
    "performance_ast": "assists",
    "performance_g_minus_pk": "goals_minus_pk",
    "performance_pk": "penalties",
    "performance_pkatt": "penalty_attempted",
    "performance_crdy": "yellows",
    "performance_crdr": "reds",
    "per_90_minutes_gls": "goals_per_90",
    "per_90_minutes_ast": "assits_per_90",
    "per_90_minutes_g_plus_a": "goals_plus_assists_per_90",
    "per_90_minutes_g_minus_pk": "goals_minus_pens_per_90",
    "per_90_minutes_g_plus_a_minus_pk": "goals_plus_assits_minus_pens_per_90",
    "expected_xg": "xg",
    "expected_npxg": "non_penalty_xg",
    "expected_xag": "expected_assists",
    "expected_npxg_plus_xag": "non_penalty_xg_plus_expected_assists",
    "per_90_minutes_xg": "xg_per_90",
    "per_90_minutes_xag": "expected_assists_per_90",
    "per_90_minutes_xg_plus_xag": "xg_plus_expected_assists_per_90",
    "per_90_minutes_npxg": "non_penalty_xg_per_90",
    "per_90_minutes_npxg_plus_xag": "non_penalty_xg_plus_expected_assists_per_90",
    "matches": "matches",
}

TEAM_DEFENSE_RENAME_COL_DICT = {
    "squad": "team",
    "no_pl": "no_players_used",
    "90s": "no_of_nineties",
    "tackles_tkl_per_match": "tackles_per_match",
    "tackles_tklw_per_match": "tackles_won_per_match",
    "tackles_def_3rd_per_match": "tackles_def_3rd_per_match",
    "tackles_mid_3rd_per_match": "tackles_mid_3rd_per_match",
    "tackles_att_3rd_per_match": "tackles_att_3rd_per_match",
    "vs_dribbles_tkl_per_match": "successful_tackles_on_dribblers_per_match",
    "vs_dribbles_att_per_match": "attempted_tackles_on_dribblers_per_match",
    "vs_dribbles_past_per_match": "unsuccessful_tackles_on_dribblers_per_match",
    "blocks_blocks_per_match": "total_blocks_per_match",
    "blocks_sh_per_match": "shots_blocked_per_match",
    "blocks_pass_per_match": "passes_blocked_per_match",
    "int_per_match": "interceptions_per_match",
    "tkl_plus_int_per_match": "tackles_plus_interceptions_per_match",
    "clr_per_match": "clearances_per_match",
    "err_per_match": "errors_per_match",
}

PLAYER_DEFENSE_RENAME_COL_DICT = {
    "Rk": "Rk",
    "Player": "player_name",
    "Nation": "country",
    "Pos": "position",
    "Squad": "team",
    "Comp": "competition",
    "Age": "age",
    "Born": "born",
    "90s": "no_of_nineties",
    "Tackles Tkl": "tackles",
    "Tackles TklW": "total_tackles_won",
    "Tackles Def 3rd": "tackles_def_3rd",
    "Tackles Mid 3rd": "tackles_mid_3rd",
    "Tackles Att 3rd": "tackles_att_3rd",
    "Vs Dribbles Tkl": "successful_tackles_on_dribblers",
    "Vs Dribbles Att": "attempted_tackles_on_dribblers",
    "Vs Dribbles Tkl%": "tackles_success_rate_percentage",
    "Vs Dribbles Past": "unsuccessful_tackles_on_dribblers",
    "Blocks Blocks": "blocks",
    "Blocks Sh": "shots_blocked",
    "Blocks Pass": "passes_blocked",
    "Int": "interceptions",
    "Tkl+Int": "tackles_plus_interceptions",
    "Clr": "clearances",
    "Err": "errors",
    "Matches": "matches",
}

TEAM_POSSESSION_RENAME_COL_DICT = {
    "Squad": "team",
    "# Pl": "no_players_used",
    "Poss": "possession",
    "90s": "no_of_nineties",
    "Touches Touches": "touches",
    "Touches Def Pen": "touches_in_defensive_penalty_area",
    "Touches Def 3rd": "touches_in_defensive_third",
    "Touches Mid 3rd": "touches_in_midfield_third",
    "Touches Att 3rd": "touches_in_attacking_third",
    "Touches Att Pen": "touches_in_attacking_penalty_area",
    "Touches Live": "live_ball_touches",
    "Dribbles Succ": "successful_dribbles",
    "Dribbles Att": "attempted_dribbles",
    "Dribbles Succ%": "dribbles_success_rate",
    "Dribbles Mis": "no_miscontrol",
    "Dribbles Dis": "no_dispossessed",
    "Receiving Rec": "passes_recieved",
    "Receiving Prog": "progressive_passess_recieved",
}
